---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: tools
  - name: repo
  - name: repo-with-tags
  - name: version
outputs:
  - name: out
caches:
  - path: gradle
  - path: maven
run:
  path: tools/concourse/tasks/test-compare-to-prod/task.sh
